from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView


from app1.views import (
    account_logout_view,
    admin_approve_company_view,
    admin_verify_company_offline_view,
    admin_login_view,
    admin_logout_view,
    admin_reject_company_view,
    candidate_application_status_view,
    candidate_applications_view,
    candidate_dashboard_view,
    candidate_feed_view,
    candidate_job_apply_view,
    candidate_job_detail_view,
    candidate_job_offers_view,
    candidate_network_view,
    candidate_profile_view,
    candidate_quizzes_view,
    candidate_register_view,
    candidate_signin_view,
    candidate_settings_view,
    company_application_detail_view,
    company_applications_view,
    company_dashboard_view,
    company_job_delete_view,
    company_job_edit_view,
    company_job_toggle_view,
    company_jobs_view,
    company_pending_approval_view,
    company_post_job_view,
    company_profile_view,
    company_register_view,
    company_signin_view,
    home,
    password_reset_view,
    signin_view,
    post_like_view,
    post_comment_view,
    toggle_follow_view,
)

urlpatterns = [
    path('', home, name='home'),
    path('signin', signin_view, name='signin'),
    path('candidate/signin', candidate_signin_view, name='candidate_signin'),
    path('company/signin', company_signin_view, name='company_signin'),
    path('logout', account_logout_view, name='account_logout'),
    path('candidate/dashboard', candidate_dashboard_view),
    path('candidate/profile', candidate_profile_view),
    path('candidate/jobs', candidate_job_offers_view),
    path('candidate/jobs/<int:job_id>', candidate_job_detail_view),
    path('candidate/jobs/<int:job_id>/apply', candidate_job_apply_view),
    path('candidate/dashboard/', candidate_dashboard_view, name='candidate_dashboard'),
    path('candidate/profile/', candidate_profile_view, name='candidate_profile'),
    path('candidate/feed', candidate_feed_view, name='candidate_feed'),
    path('candidate/jobs/', candidate_job_offers_view, name='candidate_job_offers'),
    path('candidate/job-offers', candidate_job_offers_view),
    path('candidate/jobs/<int:job_id>/', candidate_job_detail_view, name='candidate_job_detail'),
    path('candidate/jobs/<int:job_id>/apply/', candidate_job_apply_view, name='candidate_job_apply'),
    path('candidate/applications', candidate_applications_view, name='candidate_applications'),
    path('candidate/application-status', candidate_application_status_view, name='candidate_application_status'),
    path('candidate/quizzes', candidate_quizzes_view, name='candidate_quizzes'),
    path('candidate/network', candidate_network_view, name='candidate_network'),
    path('candidate/posts/<int:post_id>/like/', post_like_view, name='post_like'),
    path('candidate/posts/<int:post_id>/comment/', post_comment_view, name='post_comment'),
    path('candidate/users/<int:user_id>/follow/', toggle_follow_view, name='toggle_follow'),
    path('candidate/settings', candidate_settings_view, name='candidate_settings'),
    path('admin/login/', admin_login_view, name='admin_login_redirect'),
    path('admin/logout/', admin_logout_view, name='admin_logout_redirect'),
    path('password-reset', password_reset_view, name='password_reset'),
    path('candidate/register', candidate_register_view, name='candidate_register'),
    path('company/register', company_register_view, name='company_register'),
    path('company/pending-approval', company_pending_approval_view, name='company_pending_approval'),
    path('company/dashboard', company_dashboard_view),
    path('company/dashboard/', company_dashboard_view, name='company_dashboard'),
    path('company/profile/', company_profile_view, name='company_profile'),
    path('company/jobs/', company_jobs_view, name='company_jobs'),
    path('company/jobs/post/', company_post_job_view, name='company_post_job'),
    path('company/jobs/<int:job_id>/edit/', company_job_edit_view, name='company_job_edit'),
    path('company/jobs/<int:job_id>/toggle/', company_job_toggle_view, name='company_job_toggle'),
    path('company/jobs/<int:job_id>/delete/', company_job_delete_view, name='company_job_delete'),
    path('company/applications/', company_applications_view, name='company_applications'),
    path('company/applications/<int:application_id>/', company_application_detail_view, name='company_application_detail'),
    path('admin/approve-company/<int:company_id>/', admin_approve_company_view, name='admin_approve_company'),
    path('admin/reject-company/<int:company_id>/', admin_reject_company_view, name='admin_reject_company'),
    path('admin/verify-company-offline/<int:company_id>/', admin_verify_company_offline_view, name='admin_verify_company_offline'),
    path('admin/', admin.site.urls),
    path('test-oauth-error/', TemplateView.as_view(template_name='socialaccount/authentication_error.html'), name='test_oauth_error'),
]


if settings.HAS_ALLAUTH:
    urlpatterns.append(path('auth/', include('allauth.urls')))

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
