# Generated by Django 6.0.4 on 2026-05-23 00:33

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_joboffer_contract_type_alter_joboffer_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='ice',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ICE (15 digits)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='legal_document',
            field=models.FileField(blank=True, null=True, upload_to=app1.models.company_profile_file_path),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='rc_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registre du Commerce (RC)'),
        ),
    ]
